#ifndef _METERPRETER_SOURCE_EXTENSION_JOKEMSG_JOKEMSG_H
#define _METERPRETER_SOURCE_EXTENSION_JOKEMSG_JOKEMSG_H

#define TLV_TYPE_EXTENSION_JOKEMSG	0

#define TLV_TYPE_JOKEMSG_MESSAGE			\
			MAKE_CUSTOM_TLV(				\
				TLV_META_TYPE_STRING,		\
				TLV_TYPE_EXTENSION_JOKEMSG, \
				TLV_EXTENSIONS + 1			\
			)

#define TLV_TYPE_JOKEMSG_RESULT				\
			MAKE_CUSTOM_TLV(				\
				TLV_META_TYPE_BOOL,			\
				TLV_TYPE_EXTENSION_JOKEMSG,	\
				TLV_EXTENSIONS + 2			\
			)

#endif